# Generated by Django 6.0 on 2025-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_language',
            field=models.CharField(default='en_US', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='ui_theme',
            field=models.CharField(default='light', max_length=32),
        ),
    ]
