# Generated by Django 6.0 on 2025-12-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ui_language_user_ui_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ui_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ui_theme',
            new_name='theme',
        ),
    ]
